# Generated by Django 5.1.3 on 2024-11-12 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomize',
            name='perfilID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_customize', to='perfil.profile'),
        ),
        migrations.AddField(
            model_name='usercustomize',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usercustomize_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='permissions',
            name='role',
            field=models.ManyToManyField(related_name='permission', to='authentication.roles'),
        ),
        migrations.AddField(
            model_name='usercustomize',
            name='roleID',
            field=models.ManyToManyField(related_name='user_customize', to='authentication.roles'),
        ),
    ]
