# Generated by Django 5.1.3 on 2024-11-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_usercustomize_perfilid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustomize',
            old_name='perfilID',
            new_name='perfil',
        ),
    ]
