# Generated by Django 5.1.3 on 2024-11-14 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_perfilid_usercustomize_perfil'),
        ('perfil', '0004_alter_profile_edad_alter_profile_nivedu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomize',
            name='perfil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_customize', to='perfil.profile'),
        ),
    ]
