# Generated by Django 5.1.3 on 2024-11-14 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_usercustomize_perfil'),
        ('perfil', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomize',
            name='perfil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_customize', to='perfil.profile'),
        ),
    ]
