# Generated by Django 5.1.3 on 2024-11-14 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_usercustomize_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustomize',
            name='perfil',
        ),
    ]
