# Generated by Django 5.1.3 on 2024-11-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_rename_userid_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nivEdu',
            field=models.IntegerField(),
        ),
    ]
