# Generated by Django 5.1.3 on 2024-12-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('docente', '0002_rename_user_id_teacher_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='EducationalProgram',
        ),
    ]
