# Generated by Django 5.1.3 on 2024-12-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_rename_courses_educationalprogram'),
        ('docente', '0002_rename_user_id_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalprogram',
            name='teacher',
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='teacher',
            field=models.ManyToManyField(null=True, related_name='programs', to='docente.teacher'),
        ),
    ]
