# Generated by Django 5.1.3 on 2024-12-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_remove_educationalprogram_teacher_and_more'),
        ('docente', '0002_rename_user_id_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalprogram',
            name='teacher',
            field=models.ManyToManyField(related_name='programs', to='docente.teacher'),
        ),
    ]
