# Generated by Django 5.1.3 on 2024-12-10 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_category_alter_educationalprogram_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory', to='cursos.subcategory')),
            ],
        ),
    ]
