# Generated by Django 5.1.3 on 2024-12-10 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_especification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogram',
            name='tutor',
            field=models.ManyToManyField(related_name='tutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='status',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
