# Generated by Django 5.1.3 on 2024-12-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_educationalprogram_tutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalprogram',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
