# Generated by Django 5.1.3 on 2024-12-12 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_alter_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especification',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
