# Generated by Django 5.1.3 on 2024-12-14 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_rename_sub_category_especification_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogram',
            name='specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educationalProgram', to='cursos.especification'),
        ),
        migrations.AddField(
            model_name='educationalprogram',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educationalProgram', to='cursos.subcategory'),
        ),
        migrations.AlterField(
            model_name='educationalprogram',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorys', to='cursos.category'),
        ),
        migrations.AlterField(
            model_name='especification',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especification', to='cursos.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory', to='cursos.category'),
        ),
    ]
