# Generated by Django 5.1.3 on 2024-12-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_educationalprogram_specification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalprogram',
            name='tutor',
        ),
    ]
