# Generated by Django 5.1.3 on 2024-12-24 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_remove_educationalprogram_tutor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogram',
            name='tutor',
            field=models.ManyToManyField(related_name='tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
