# Generated by Django 5.1.3 on 2025-01-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_remove_educationalprogram_tutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprogram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
