# Generated by Django 5.1.3 on 2025-03-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0016_educationalprogram_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='especification',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='especification',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
